# Generated by Django 5.0.1 on 2024-03-30 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider_name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Phone_no', models.CharField(max_length=13)),
                ('Business_name', models.CharField(max_length=80)),
                ('GST_id', models.CharField(max_length=15)),
                ('Business_address', models.CharField(max_length=300)),
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=60)),
                ('Vehicle_model', models.CharField(max_length=50)),
                ('Vehicle_number', models.CharField(max_length=10)),
                ('Chassis_no', models.CharField(max_length=17)),
                ('Fuel_type', models.CharField(max_length=20)),
                ('Transmission_type', models.CharField(max_length=20)),
                ('Seating_capacity', models.IntegerField()),
                ('Rent_price', models.IntegerField()),
                ('Vehicle_img1', models.ImageField(upload_to='')),
                ('Img_insurance', models.ImageField(upload_to='')),
                ('Provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.provider')),
            ],
        ),
    ]
