# Generated by Django 5.0.1 on 2024-04-26 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='Earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Payment_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Pay_date_time', models.DateTimeField()),
                ('Invoice_no', models.CharField(max_length=10)),
                ('Provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.provider')),
                ('Vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.vehicle')),
            ],
        ),
    ]
