# Generated by Django 5.0.1 on 2024-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0003_payment_provider_admin_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_provider',
            name='Admin_commission',
            field=models.IntegerField(),
        ),
    ]
