# Generated by Django 5.0.1 on 2024-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0004_alter_payment_provider_admin_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Earnings',
            field=models.IntegerField(),
        ),
    ]
