# Generated by Django 5.0.1 on 2024-04-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0005_alter_provider_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Earnings',
            field=models.IntegerField(default=0),
        ),
    ]
