# Generated by Django 5.0.1 on 2024-03-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provider', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.IntegerField()),
                ('User_id', models.IntegerField()),
                ('Provider_id', models.IntegerField()),
                ('Message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Pay_date_time', models.DateField()),
                ('Invoice_no', models.IntegerField()),
                ('Provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_start_date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Starting_location', models.CharField(max_length=300)),
                ('Ending_location', models.CharField(max_length=300)),
                ('Provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.provider')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('Vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.vehicle')),
                ('Payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategory', models.CharField(max_length=100)),
                ('Cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.category')),
            ],
        ),
    ]
