# Generated by Django 5.0.1 on 2024-04-22 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_booking_payment_id'),
        ('Provider', '0001_initial'),
        ('User', '0003_alter_user_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Provider_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='Vehicle_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Provider.vehicle'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
