# Generated by Django 5.0.1 on 2024-04-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_payment_provider_id_payment_vehicle_id_and_more'),
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.vehicle'),
        ),
    ]
