# Generated by Django 5.0.1 on 2024-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_payment_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Invoice_no',
            field=models.CharField(max_length=10),
        ),
    ]
