# Generated by Django 5.0.1 on 2024-04-23 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_payment_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='B_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='B_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Pay_date_time',
            field=models.DateTimeField(),
        ),
    ]
