# Generated by Django 5.0.1 on 2024-04-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_remove_booking_duration_booking_b_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='B_end_date',
            field=models.DateTimeField(),
        ),
    ]
