# Generated by Django 5.0.1 on 2024-04-26 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_booking_b_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='booking',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 34, 44, 452812)),
        ),
    ]
