# Generated by Django 5.0.1 on 2024-04-26 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_alter_booking_created_at_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='A_earnings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 40, 46, 749356)),
        ),
    ]
