# Generated by Django 5.0.1 on 2024-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_admin_a_earnings_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Created_at',
            field=models.DateTimeField(),
        ),
    ]
