# Generated by Django 5.0.1 on 2024-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_alter_booking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_earnings', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
