# Generated by Django 5.0.1 on 2024-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_admin_earnings_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Created_at',
            field=models.DateField(),
        ),
    ]
