# Generated by Django 5.0.1 on 2024-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Deposit',
            field=models.IntegerField(default=0),
        ),
    ]
