# Generated by Django 5.0.1 on 2024-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Deposit',
            field=models.IntegerField(),
        ),
    ]
